### ISSUE TITLE
Multiline patterns

### ISSUE THREAD

**Issue by lowlyocean** [nickgammon/Regexp#10]
Having trouble capturing a value in an HTML table because the HTML returned by the server defines each cell of the table on a new line. I can use PCRE succesfully, but not sure whether Lua's regex supports this?

**Comment by nickgammon** [comment]
Lua's patterns are not as sophisticated as PCRE. You could try using the "non-greedy" wildcard matching.

You might be able to just parse "on the fly" by using a state machine. If things aren't heavily nested you can detect a "<" symbol, look for what word follows that, and then interpret accordingly. This can save RAM because you don't have to keep the whole document in memory to achieve this.

**Comment by lowlyocean** [comment]
Thanks, been trying to use non-greedy wildcard matching and hoping to avoid writing anything resembling a parser myself; is it specified whether "." in Lua will capture linefeed or carriage return? I may also try to find an HTML DOM parser - not sure if https://github.com/google/gumbo-parser will fit

**Comment by nickgammon** [comment]
You can find that out for yourself using Lua, eg.

```lua
s = "ab\ncd"

print (string.find (s, ".+"))
```

That prints "1 5" which indicates that the "." captured the newline.

The regexp library is basically Lua patterns placed into a library for use with the Arduino.

**Comment by lowlyocean** [comment]
I didn't setup a Lua environment. In any case, it turns out the WiShield library I was using returns the HTTP response body in  chunks of 330 bytes. My multiline pattern wasn't working because of this. So I added state to tell during which chunk a simpler pattern should be expected. It's been working but now my issue is when the pattern appears half in one chunk and half in the next. Maintaining a "crossover" ringbuffer is an obvious solution but I must be making a bad assumption about the buffer being passed to my callback. TBD
